// Code generated by goctl. DO NOT EDIT.
package types

type MsgRequest struct {
	MsgSignature string `form:"msg_signature"`
	TimeStamp    string `form:"timestamp"`
	Nonce        string `form:"nonce"`
	EchoStr      string `form:"echostr,optional"`
}

type MsgResponse struct {
	ErrCode int    `json:"err_code"`
	ErrMsg  string `json:"err_msg"`
	Data    []byte `json:"data"`
}
